version: "3.5"
volumes:
  datavolume: {}
services:
  redis:
    container_name: hydro-scaffold-dex-redis
    image: redis:5.0
    ports:
      - 127.0.0.1:6379:6379
    restart: always
    logging: &logging_default
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200m"
        # compress: "true"
    networks:
            dex-network:
                aliases:
                    - dex-redis
  ethereum-node:
    container_name: hydro-scaffold-dex-ethereum-node
    image: hydroprotocolio/hydro-scaffold-dex-ethereum-node:latest
    ports:
      - 127.0.0.1:8545:8545
    restart: always
    logging:
      <<: *logging_default
    networks:
            dex-network:
                aliases:
                    - dex-eth
  db:
    container_name: hydro-scaffold-dex-pg
    image: postgres
    ports:
      - 127.0.0.1:5432:5432
    restart: always
    logging:
      <<: *logging_default
    volumes:
      - datavolume:/var/lib/postgresql/data
      - ./backend/db/migrations/0001-init.up.sql:/docker-entrypoint-initdb.d/0001-init.up.sql
      - ./envs/localhost/seed.sql:/docker-entrypoint-initdb.d/0002-seed.sql
    networks:
            dex-network:
                aliases:
                    - dex-db
  web:
    image: hydroprotocolio/hydro-scaffold-dex-web:latest
    container_name: hydro-scaffold-dex-web
    ports:
      - 127.0.0.1:3000:8043
    environment:
      - CONFIG_VARS=REACT_APP_API_URL,REACT_APP_WS_URL,REACT_APP_NODE_URL,REACT_APP_HYDRO_PROXY_ADDRESS,REACT_APP_HYDRO_TOKEN_ADDRESS,REACT_APP_WETH_TOKEN_ADDRESS,REACT_APP_NETWORK_ID
      - REACT_APP_API_URL=http://www.dex-demo-api.hydroprotocol.io
      - REACT_APP_WS_URL=ws://www.dex-demo-ws.hydroprotocol.io
      - REACT_APP_NODE_URL=https://api.baobab.klaytn.net:8651
      - REACT_APP_HYDRO_PROXY_ADDRESS=0xf72920Fe61945DF67d8a24d0122a0bb1EC23AbB5
      - REACT_APP_HYDRO_TOKEN_ADDRESS=0x60E28B048dE9F8BceDBf07Ec0c4829dfFB9A2A7d
      - REACT_APP_WETH_TOKEN_ADDRESS=0x53A627E57adED2b784Ee45657BB5D02E8f676fA0
      - REACT_APP_NETWORK_ID=1001
    restart: always
    logging:
      <<: *logging_default
    networks:
            dex-network:
                aliases:
                    - dex-web
  admin:
    image: hydroprotocolio/hydro-scaffold-dex-backend:latest
    container_name: hydro-scaffold-dex-admin-api
    command: /bin/adminapi
    ports:
      - 127.0.0.1:3003:3003
    environment:
      - HSK_DATABASE_URL=postgres://postgres:postgres@db/postgres?sslmode=disable
      - HSK_REDIS_URL=redis://redis:6379/0
      - HSK_BLOCKCHAIN_RPC_URL=https://api.baobab.klaytn.net:8651
      - HSK_LOG_LEVEL=ERROR
      - WEB_HEALTH_CHECK_URL=http://web:8043
      - API_HEALTH_CHECK_URL=http://api:4001/metrics
      - ENGINE_HEALTH_CHECK_URL=http://engine:4004/metrics
      - LAUNCHER_HEALTH_CHECK_URL=http://launcher:4005/metrics
      - WATCHER_HEALTH_CHECK_URL=http://watcher:4003/metrics
      - WEBSOCKET_HEALTH_CHECK_URL=http://ws:4002/metrics
      - HSK_PROXY_ADDRESS=0xf72920Fe61945DF67d8a24d0122a0bb1EC23AbB5
      - HSK_RELAYER_ADDRESS=0x5C9bDED4dfDBB3D6b489A45b5b37023c54E0AAaa
    volumes:
      - datavolume:/data
    depends_on:
      - db
      - redis
      - ethereum-node
    restart: always
    logging:
      <<: *logging_default
    networks:
            dex-network:
                aliases:
                    - dex-admin
  api:
    image: hydroprotocolio/hydro-scaffold-dex-backend:latest
    container_name: hydro-scaffold-dex-api
    command: /bin/api
    ports:
      - 127.0.0.1:3001:3001
      - 127.0.0.1:4001:4001
    environment:
      - HSK_DATABASE_URL=postgres://postgres:postgres@db/postgres?sslmode=disable
      - HSK_REDIS_URL=redis://redis:6379/0
      - HSK_HYBRID_EXCHANGE_ADDRESS=0x5e18ac78341be8CF8BbAf4BABB4780Ba9804eAdD
      - HSK_BLOCKCHAIN_RPC_URL=https://api.baobab.klaytn.net:8651
      - HSK_HYDRO_TOKEN_ADDRESS=0x60E28B048dE9F8BceDBf07Ec0c4829dfFB9A2A7d
      - HSK_PROXY_ADDRESS=0xf72920Fe61945DF67d8a24d0122a0bb1EC23AbB5
      - HSK_RELAYER_ADDRESS=0x5C9bDED4dfDBB3D6b489A45b5b37023c54E0AAaa
      - HSK_LOG_LEVEL=DEBUG
      - METRICS_PORT=4001
      - HSK_PROXY_MODE=deposit
    volumes:
      - datavolume:/data
    depends_on:
      - db
      - redis
    restart: always
    logging:
      <<: *logging_default
    networks:
            dex-network:
                aliases:
                    - dex-api
  ws:
    image: hydroprotocolio/hydro-scaffold-dex-backend:latest
    container_name: hydro-scaffold-dex-ws
    command: /bin/websocket
    ports:
      - 127.0.0.1:3002:3002
      - 127.0.0.1:4002:4002
    environment:
      - HSK_API_URL=http://api:3001
      - HSK_REDIS_URL=redis://redis:6379/0
      - HSK_LOG_LEVEL=DEBUG
      - METRICS_PORT=4002
    volumes:
      - datavolume:/data
    depends_on:
      - redis
      - api
    restart: always
    logging:
      <<: *logging_default
    networks:
            dex-network:
                aliases:
                    - dex-ws
  watcher:
    image: hydroprotocolio/hydro-scaffold-dex-backend:latest
    container_name: hydro-scaffold-dex-watcher
    command: /bin/watcher
    ports:
      - 127.0.0.1:4003:4003
    environment:
      - HSK_DATABASE_URL=postgres://postgres:postgres@db/postgres?sslmode=disable
      - HSK_REDIS_URL=redis://redis:6379/0
      - HSK_BLOCKCHAIN_RPC_URL=https://api.baobab.klaytn.net:8651
      - HSK_LOG_LEVEL=DEBUG
      - HSK_HYBRID_EXCHANGE_ADDRESS=0x5e18ac78341be8CF8BbAf4BABB4780Ba9804eAdD
      - METRICS_PORT=4003
    volumes:
      - datavolume:/data
    depends_on:
      - redis
      - db
      - ethereum-node
    restart: always
    logging:
      <<: *logging_default
    networks:
            dex-network:
                aliases:
                    - dex-watcher
  engine:
    image: hydroprotocolio/hydro-scaffold-dex-backend:latest
    container_name: hydro-scaffold-dex-engine
    command: /bin/engine
    ports:
      - 127.0.0.1:4004:4004
    environment:
      - HSK_DATABASE_URL=postgres://postgres:postgres@db/postgres?sslmode=disable
      - HSK_REDIS_URL=redis://redis:6379/0
      - HSK_HYBRID_EXCHANGE_ADDRESS=0x5e18ac78341be8CF8BbAf4BABB4780Ba9804eAdD
      - HSK_PROXY_ADDRESS=0xf72920Fe61945DF67d8a24d0122a0bb1EC23AbB5
      - HSK_LOG_LEVEL=DEBUG
      - METRICS_PORT=4004
    volumes:
      - datavolume:/data
    depends_on:
      - redis
      - db
    restart: always
    logging:
      <<: *logging_default
    networks:
            dex-network:
                aliases:
                    - dex-engine
  launcher:
    image: hydroprotocolio/hydro-scaffold-dex-backend:latest
    container_name: hydro-scaffold-dex-launcher
    command: /bin/launcher
    ports:
      - 127.0.0.1:4005:4005
    environment:
      - HSK_DATABASE_URL=postgres://postgres:postgres@db/postgres?sslmode=disable
      - HSK_BLOCKCHAIN_RPC_URL=https://api.baobab.klaytn.net:8651
      - HSK_HYBRID_EXCHANGE_ADDRESS=0x5e18ac78341be8CF8BbAf4BABB4780Ba9804eAdD
      - HSK_RELAYER_ADDRESS=0xf2307ef1f4f142e75eb2b758efe50b0bf59ae040
      - HSK_RELAYER_PK=87e556ff0ba2ed2d57feec46a36a54b943dde52f24f8b92216a18e2fce444a10
      - HSK_LOG_LEVEL=DEBUG
      - METRICS_PORT=4005
    volumes:
      - datavolume:/data
    depends_on:
      - db
      - ethereum-node
    restart: always
    logging:
      <<: *logging_default
    networks:
            dex-network:
                aliases:
                    - dex-engine
  maker:
    image: hydroprotocolio/amm-bots
    container_name: hydro-scaffold-dex-maker
    depends_on:
      - api
    environment:
      - BOT_TYPE=CONST_PRODUCT
      - BOT_PRIVATE_KEY=0xa6553a3cbade744d6c6f63e557345402abd93e25cd1f1dba8bb0d374de2fcf4f
      - BOT_BASE_TOKEN=HOT
      - BOT_QUOTE_TOKEN=DAI
      - BOT_BASE_URL=http://api:3001
      - BOT_MIN_PRICE=0.8
      - BOT_MAX_PRICE=1.2
      - BOT_PRICE_GAP=0.02
      - BOT_EXPAND_INVENTORY=2
      - BOT_WEB3_URL=http://ethereum-node:8545
    restart: on-failure:10
    logging:
      <<: *logging_default
    networks:
            dex-network:
                aliases:
                    - dex-maker
  nginx:
    image: nginx
    container_name: nginx
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - web
      - api
      - ws
    networks:
            dex-network:
                aliases:
                    - dex-nginx
networks:
    dex-network:
